source 'https://rubygems.org'
ruby '2.2.3'

# Middleman
gem 'middleman', '~> 3.3.10'
gem 'middleman-gh-pages', '~> 0.0.3'
gem 'middleman-syntax', '~> 2.0.0'
gem 'middleman-autoprefixer', '~> 2.4.4'

gem 'rouge', '~> 1.9.0'
gem 'redcarpet', '~> 3.3.2'

gem 'rake', '~> 10.4.2'
gem 'therubyracer', '~> 0.12.2', platforms: :ruby
